### ISSUE TITLE
Fix Join Us Button

### ISSUE THREAD

**Issue by Bhavya0404** [dsc-jiit-128/Hactoberfest-website#10]
Add the same link of Contact us to the Join Button.

**Comment by princekushwaha** [comment]
I want to work on this.

**Comment by Bhavya0404** [comment]
@princekushwaha  I have assigned the task to you

**Comment by princekushwaha** [comment]
will this PR will be accepted in hacktoberfest now

**Comment by Bhavya0404** [comment]
Yes, it will be counted @princekushwaha
