### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by Bhavya0404** [dsc-jiit-128/Hactoberfest-website#11]
![image](https://user-images.githubusercontent.com/51115215/135578375-6ae75d1b-34b8-47bd-a2fb-94e74cd10e2f.png)

Remove the scroll from all of the navbar

**Comment by PiyushNadoda** [comment]
I have faced this problem many times. I can fix this.

**Comment by sarthakpant772** [comment]
@PiyushNadoda You are assigned to this task. You need to finish this task within three days. All the best!

**Comment by PiyushNadoda** [comment]
@sarthakpant772 done. Check it out.

**Comment by yashashxrma** [comment]
can I try to improve this

**Comment by HiruniPerera** [comment]
Hi, can Work on this
