### ISSUE TITLE
Size issue on Goodies page

### ISSUE THREAD

**Issue by Bhavya0404** [dsc-jiit-128/Hactoberfest-website#12]
make the size of images and text small

**Comment by niku123K** [comment]
Shall I do this?

**Comment by niku123K** [comment]
Shall I do this,please?

**Comment by NarayanBavisetti** [comment]
can you assign this issue to me. I want to fix it.

**Comment by Bhavya0404** [comment]
@niku123K  You are assigned to this task. You need to finish this task within three days.

**Comment by Bhavya0404** [comment]
@NarayanBavisetti  if @niku123K  does not complete his task within the assigned date this task will be assigned to you. Till then feel free to contribute towards other issues or make your own issues.
