### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by Bhavya0404** [dsc-jiit-128/Hactoberfest-website#14]
make a new FAQ page

**Comment by princekushwaha** [comment]
What questions have to write in FAQ?

**Comment by NarayanBavisetti** [comment]
I can make the FAQ page. Can you assign me

**Comment by Bhavya0404** [comment]
> What questions have to write in FAQ?

General doubts which new people face.

**Comment by yashashxrma** [comment]
can i work on this

**Comment by Bhavya0404** [comment]
@NarayanBavisetti  You are assigned to this task. You need to finish this task within three days.

**Comment by Bhavya0404** [comment]
Hey @NarayanBavisetti  are you working on this issue?

**Comment by NarayanBavisetti** [comment]
yes, sorry for the delay I will complete the page by today

**Comment by kwoctcrazy** [comment]
Can I do this one?

**Comment by Bhavya0404** [comment]
> Can I do this one?

Hey @kwoctcrazy  Someone else is working on this issue right now...You can explore other issues or create a new one!
