### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by Bhavya0404** [dsc-jiit-128/Hactoberfest-website#24]
Spelling Error on first Page

**Comment by sakuraixiao** [comment]
can you assign me this?

**Comment by sarthakpant772** [comment]
can you assign me this task

**Comment by Bhavya0404** [comment]
Yes @sarthakpant772  Go ahead!

**Comment by abhishikta-41** [comment]
I would like to work on this issue.  Can you please assign it to me?
