### ISSUE TITLE
GDSC Logo

### ISSUE THREAD

**Issue by Bhavya0404** [dsc-jiit-128/Hactoberfest-website#32]
Need GDSC logo on all the Pages.

![image](https://user-images.githubusercontent.com/51115215/135722076-3b11aae8-68c9-4ce5-a078-fbb0b0faa93e.png)

**Comment by shrutij11** [comment]
can you please assign this issue to me.I can solve this.

**Comment by Bhavya0404** [comment]
@shrutij11  You are assigned to this task. You need to finish this task within three days.

**Comment by CoderNehal** [comment]
Assign me this @Bhavya0404
