### ISSUE TITLE
Improve the formatting effects of the button on about hacktoberfest page

### ISSUE THREAD

**Issue by agarwalrashika00** [dsc-jiit-128/Hactoberfest-website#42]
give the button a nice look which also matches the *color scheme* of the page, show your creativity here ;)

![image](https://user-images.githubusercontent.com/56035062/135733255-48891402-9a92-412b-83bc-a850dbb32004.png)

**Comment by ab80four** [comment]
May I give this a shot please?

**Comment by SmashedTrash** [comment]
Hey I can do it can you assign it to me

**Comment by agarwalrashika00** [comment]
This issue is closed now. Try some other issues mentioned in the issues section.
