### ISSUE TITLE
Animations Along With Change In Font Styles And Some Changes In The Navbar

### ISSUE THREAD

**Issue by code08-ind** [dsc-jiit-128/Hactoberfest-website#47]
Animations On Scroll And Other Animations Along With Change In Font Styles And Some Changes In The Navbar. Please Assign Me This Issue And I Assure You That The Website Will Look Awesome.

**Comment by sudeepkhandekar99** [comment]
Please assign me this task!

**Comment by code08-ind** [comment]
I m not the maintainer of this repo.

**Comment by Bhavya0404** [comment]
> Animations On Scroll And Other Animations Along With Change In Font Styles And Some Changes In The Navbar. Please Assign Me This Issue And I Assure You That The Website Will Look Awesome.

go ahead!

**Comment by code08-ind** [comment]
Thanks. Will Do It By Tomorrow

**Comment by code08-ind** [comment]
Issue Fulfilled By Filling In PR And Merged Finally.
