### ISSUE TITLE
Improve UI of About section

### ISSUE THREAD

**Issue by rucha0702** [dsc-jiit-128/Hactoberfest-website#54]
About section can be improved lookwise.

**Comment by rucha0702** [comment]
Can I work on this?

**Comment by Bhavya0404** [comment]
I have assigned this issue to you @rucha0702 . Just improve the UI dont make it responsive.

**Comment by rucha0702** [comment]
Okay! will do. Thanks for assigning.

**Comment by rucha0702** [comment]
I have updated the UI. @Bhavya0404
