### ISSUE TITLE
Adding Footer

### ISSUE THREAD

**Issue by Pensuveze** [dsc-jiit-128/Hactoberfest-website#8]
Footer with social media links, privacy policy etc...

**Comment by Pensuveze** [comment]
@dscjiit128 I want to contribute in this project. Please assign it to me.
Thanks.

**Comment by IshitaSingh23** [comment]
hey @dscjiit128 I would want to contribute to this project !

**Comment by Bhavya0404** [comment]
@Pensuveze  You are assigned to this task. You need to finish this task within three days.

**Comment by Bhavya0404** [comment]
@IshitaSingh23  if @Pensuveze  does not complete his task within the assigned date this task will be assigned to you. Till then feel free to contribute towards other issues or make your own issues.

**Comment by Pensuveze** [comment]
@IshitaSingh23 Mam i added the footer successfully .
your instagram and facebook links are not active please provide me the accessible links so that i can place the at necessary place ..
Please ...
Thanks ..

**Comment by Pensuveze** [comment]
@Bhavya0404 Mam i added the footer successfully .
your instagram and facebook links are not active please provide me the accessible links so that i can place the at necessary place ..
Please ...
Thanks ..

**Comment by HiruniPerera** [comment]
Hello i would love to contribute to this project? can u assign me this task and also can you tell me what is needed to be done ?

**Comment by Pensuveze** [comment]
@HiruniPerera I am already working on it so please find another one ..
